### ISSUE TITLE
remove .env file

### ISSUE THREAD

**Issue by trong-le** [aries-data/aries-activity-stripe-source#4]
.env file shouldn't be here. has someone's stripe key in it.

**Comment by benjamingregory** [comment]
@trong-le I think it was just a test key so we should be ok but @jlaneve can you confirm?

**Comment by jlaneve** [comment]
@benjamingregory yep, just a test key under a personal account. Never used. @trong-le thanks for pointing it out

**Comment by benjamingregory** [comment]
Will resolve with #5
